baseURL: "https://samuel-chlam.github.io/masterplan-2022/"
title: Samuel Lam's Blogs
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Samuel's Blogs"
    description: "The site documents my masterplan, reviews and teaching pages."
    keywords: [Blog, Portfolio, PaperMod]
    author: "Samuel Lam"
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    math: True

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        # favicon: "<link / abs url>"
        # favicon16x16: "<link / abs url>"
        # favicon32x32: "<link / abs url>"
        # apple_touch_icon: "<link / abs url>"
        # safari_pinned_tab: "<link / abs url>"

    label:
        text: "Samuel's Master Plan 2022"
        # icon: /apple-touch-icon.png
        # iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "It has been 20.5 years - what's next?"
        Content: > 
          Time flies and it has been 2023, and I am delighted to have graduated from Imperial College London and joined the CDT Mathematics of Random Systems. 
          This webpage contains my original masterplans, review, as well as (teaching) announcements.

          - The main goal of the master plan is to **develop a healthier lifestyle, have breakthroughs in mathematics 
          and contribute to the sustainable development of the communities I am engaging in, including the mathematics and Christian communities.**

          - Checkout the following five categories: [*lifestyle*](/masterplan-2022/lifestyle), [*academic*](/masterplan-2022/academic), [*academic-outreach*](/masterplan-2022/academic-outreach), 
          [*christianity*](/masterplan-2022/christianity) and [*personal branding*](/masterplan-2022/branding).

          - You can also sort the posts by [*categories*](/masterplan-2022/categories) and [*tags*](/masterplan-2022/tags)
          
    socialIcons:
        - name: website
          url: "https://samuel-chlam.github.io/newsite/"
        - name: facebook
          url: "https://www.facebook.com/chunhei.lam.1671/"
        - name: github
          url: "https://github.com/Samuel-CHLam"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/Samuel-CHLam/masterplan-2022/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
    main:
        - identifier: lifestyle
          name: lifestyle
          url: /lifestyle/
          weight: 1
        - identifier: academic
          name: academic
          url: /academic/
          weight: 2
        - identifier: academic-outreach
          name: outreach
          url: /academic-outreach/
          weight: 3
        - identifier: christianity
          name: christianity
          url: /christianity/
          weight: 4
        - identifier: branding
          name: personal branding
          url: /branding/
          weight: 5 
        # - identifier: archives
        #   name: archives
        #   url: /archives/
        #   weight: 10
        - identifier: categories
          name: categories
          url: /categories/
          weight: 15
        # - identifier: tags
        #   name: tags
        #   url: /tags/
        #   weight: 20
        # - identifier: example
        #   name: example.org
        #   url: https://example.org
        #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai